#!/bin/bash

chmod u+s /usr/bin/gimx /usr/bin/sixaddr /usr/bin/bdaddr /usr/bin/hcirevision /usr/bin/ds4tool

INPUT="input"

groupadd -f $INPUT

echo "KERNEL==\"event*\", NAME=\"input/%k\", MODE:=\"660\", GROUP=\"$INPUT\"" > /etc/udev/rules.d/99-gimx-input.rules
echo "KERNEL==\"js*\", NAME=\"input/%k\", MODE:=\"664\", GROUP=\"$INPUT\"" >> /etc/udev/rules.d/99-gimx-input.rules
chgrp $INPUT /dev/input/event* /dev/input/js* &> /dev/null

chgrp $INPUT /usr/bin/gimx-config /usr/bin/gimx-fpsconfig /usr/bin/gimx-launcher
chmod g+s /usr/bin/gimx-config /usr/bin/gimx-fpsconfig /usr/bin/gimx-launcher

mkdir -p /etc/X11/xorg.conf.d
echo "Section \"InputClass\"
   Identifier \"Logitech wheels managed by the UHID driver\"
   MatchUSBID \"046d:c291|046d:c293|046d:c294|046d:c295|046d:c298|046d:c299|046d:c29a|046d:c29b|046d:ca03|046d:c260\"
   Option     \"Ignore\" \"true\"
EndSection" > /etc/X11/xorg.conf.d/gimx.conf
