#!/bin/bash

#don't forget to add universe to ~/.pbuilderrc

#uncomment in a new build environment
#sudo apt-get install gdebi subversion devscripts pbuilder debhelper

VERSION=`cat version`
PACKAGE=`cat package`
TARGET_ARCH=`cat architecture`
DATE=`date -R`
BRANCH="dev"

echo "Version number? (default: "$VERSION")"

read NEW_VERSION

if [ -z $NEW_VERSION ]
then
  NEW_VERSION=$VERSION
fi

echo "Target architecture? (default: "$TARGET_ARCH")"

read NEW_TARGET_ARCH

if [ -z $NEW_TARGET_ARCH ]
then
  NEW_TARGET_ARCH=$TARGET_ARCH
fi

if [ -z $NEW_VERSION ]
then
  echo No version specified!
  exit
fi

if [ -z $NEW_TARGET_ARCH ]
then
  echo No architecture specified!
  exit
fi

echo $NEW_VERSION > version
echo $NEW_TARGET_ARCH > architecture

if [ "$NEW_TARGET_ARCH" != "$TARGET_ARCH" ]
then
  sudo pbuilder create --architecture $NEW_TARGET_ARCH
fi

wget -O fixed.html "https://github.com/matlo/GIMX/issues?labels=GIMX+$NEW_VERSION&state=closed"
FIXED=`cat fixed.html | grep "list-group-item-number" | sed 's/[^#0-9]//g' | sed ':a;N;$!ba;s/\n/ /g'`
rm fixed.html

mkdir -p $PACKAGE-$NEW_VERSION

cp -r debian $PACKAGE-$NEW_VERSION
cp Makefile $PACKAGE-$NEW_VERSION

cd $PACKAGE-$NEW_VERSION

sed -i "s/#VERSION#/$NEW_VERSION/" debian/changelog
sed -i "s/#FIXED#/$FIXED/" debian/changelog
sed -i "s/#DATE#/$DATE/" debian/changelog

nano debian/changelog

sed -i "s/#DATE#/$DATE/" debian/copyright

nano debian/copyright

git clone -b $BRANCH --single-branch --depth 1 https://github.com/matlo/GIMX.git

if [ -n $NEW_VERSION ]
then
  MAJOR=$(echo $NEW_VERSION | awk -F"." '{print $1}')
  MINOR=$(echo $NEW_VERSION | awk -F"." '{print $2}')
  echo Major release number: $MAJOR
  echo Minor release number: $MINOR
  if [ -z $MAJOR ] || [ -z $MINOR ]
  then
    echo Invalid release number!
    exit
  fi
  
  sed -i "s/#define[ ]*INFO_VERSION[ ]*\"[0-9]*.[0-9]*\"/#define INFO_VERSION \"$MAJOR.$MINOR\"/" GIMX/info.h
  sed -i "s/#define[ ]*INFO_YEAR[ ]*\"2010-[0-9]*\"/#define INFO_YEAR \"2010-$(date '+%Y')\"/" GIMX/info.h
fi

debuild --no-tgz-check -S

sudo pbuilder build ../$PACKAGE\_$NEW_VERSION-1.dsc --architecture $NEW_TARGET_ARCH

cp /var/cache/pbuilder/result/$PACKAGE\_$NEW_VERSION-1_*.deb ..

